
	<div style="background:#f9f9f9">
	<div style="background-color:#f9f9f9">

	<div style="margin:0px auto;max-width:640px;background:transparent"><table style="font-size:0px;width:100%;background:transparent" cellspacing="0" cellpadding="0" border="0" align="center"><tbody><tr><td style="text-align:center;vertical-align:top;direction:ltr;font-size:0px;padding:40px 0px"><div style="vertical-align:top;display:inline-block;direction:ltr;font-size:13px;text-align:left;width:100%"><table width="100%" cellspacing="0" cellpadding="0" border="0"><tbody><tr><td style="word-break:break-word;font-size:0px;padding:0px" align="center"><table style="border-collapse:collapse;border-spacing:0px" cellspacing="0" cellpadding="0" border="0" align="center"><tbody><tr><td style="width:138px"><a target="_blank" href="discord.com"><img src="https://cdn.discordapp.com/email_assets/2ec94ed90b8e95d764f2a1c96f33139e.png" title alt width="138" height="38px"></a></td></tr></tbody></table></td></tr></tbody></table></div></td></tr></tbody></table></div>
		  <div style="max-width:640px;margin:0 auto;border-radius:4px;overflow:hidden"><div style="margin:0px auto;max-width:640px;background:#ffffff"><table style="font-size:0px;width:100%;background:#ffffff" cellspacing="0" cellpadding="0" border="0" align="center"><tbody><tr><td style="text-align:center;vertical-align:top;direction:ltr;font-size:0px;padding:40px 50px"><div style="vertical-align:top;display:inline-block;direction:ltr;font-size:13px;text-align:left;width:100%"><table width="100%" cellspacing="0" cellpadding="0" border="0"><tbody><tr><td style="word-break:break-word;font-size:0px;padding:0px" align="left"><div style="color:#737f8d;font-family:Whitney,Helvetica Neue,Helvetica,Arial,Lucida Grande,sans-serif;font-size:16px;line-height:24px;text-align:left">

	  <h2 style="font-family:Whitney,Helvetica Neue,Helvetica,Arial,Lucida Grande,sans-serif;font-weight:500;font-size:20px;color:#4f545c;letter-spacing:0.27px">Hello Korxy,</h2>
	<p>Looks like someone tried to sign in to your Discord account from a new location. If it was you, you authorize the login from this site via the link below. If it wasn't you, we recommend that you change your password as soon as possible.</p>
	<p><b>IP-adress:</b> 11.54.156.85<br>
	<b>place:</b> USA Kansas</p>
	<p>P.S. We strongly recommend that you enable 2-factor authentication (2FA) for your account. Read more at: <a target="_blank" style="font-family:Whitney,Helvetica Neue,Helvetica,Arial,Lucida Grande,sans-serif;color:#7289da" href="discord.com">https://blog.discordapp.com/keeping-discord-safe-and-sound/</a></p>

			  </div></td></tr><tr><td style="word-break:break-word;font-size:0px;padding:10px 25px;padding-top:20px" align="center"><table style="border-collapse:separate" cellspacing="0" cellpadding="0" border="0" align="center"><tbody><tr><td style="border:none;border-radius:3px;color:white;padding:15px 19px" valign="middle" bgcolor="#7289DA" align="center"><a target="_blank" style="text-decoration:none;line-height:100%;background:#7289da;color:white;font-family:Ubuntu,Helvetica,Arial,sans-serif;font-size:15px;font-weight:normal;text-transform:none;margin:0px" href="discord.com">
				Verify Login
			  </a></td></tr></tbody></table></td></tr><tr><td style="word-break:break-word;font-size:0px;padding:30px 0px"><p style="font-size:1px;margin:0px auto;border-top:1px solid #dcddde;width:100%"></p></td></tr><tr><td style="word-break:break-word;font-size:0px;padding:0px" align="left"><div style="color:#747f8d;font-family:Whitney,Helvetica Neue,Helvetica,Arial,Lucida Grande,sans-serif;font-size:13px;line-height:16px;text-align:left">
	<p>Do you need help? <a target="_blank" style="font-family:Whitney,Helvetica Neue,Helvetica,Arial,Lucida Grande,sans-serif;color:#7289da" href="discord.com">Contact our support</a> or write too us on twitter <a target="_blank" style="font-family:Whitney,Helvetica Neue,Helvetica,Arial,Lucida Grande,sans-serif;color:#7289da" href="discord.com">@discordapp</a>.<br>
	Leave your <a target="_blank" style="font-family:Whitney,Helvetica Neue,Helvetica,Arial,Lucida Grande,sans-serif;color:#7289da" href="discord.com">feedback here</a>.</p>

	</div></td></tr></tbody></table></div></td></tr></tbody></table></div>
		  </div><div style="margin:0px auto;max-width:640px;background:transparent"><table style="font-size:0px;width:100%;background:transparent" cellspacing="0" cellpadding="0" border="0" align="center"><tbody><tr><td style="text-align:center;vertical-align:top;direction:ltr;font-size:0px;padding:0px"><div style="vertical-align:top;display:inline-block;direction:ltr;font-size:13px;text-align:left;width:100%"><table width="100%" cellspacing="0" cellpadding="0" border="0"><tbody><tr><td style="word-break:break-word;font-size:0px"><div style="font-size:1px;line-height:12px">&nbsp;</div></td></tr></tbody></table></div></td></tr></tbody></table></div>
		  <div style="margin:0 auto;max-width:640px;background:#ffffff;border-radius:4px;overflow:hidden"><table style="font-size:0px;width:100%;background:#ffffff" cellspacing="0" cellpadding="0" border="0" align="center"><tbody><tr><td style="text-align:center;vertical-align:top;font-size:0px;padding:0px"><div style="vertical-align:top;display:inline-block;direction:ltr;font-size:13px;text-align:left;width:100%"><table width="100%" cellspacing="0" cellpadding="0" border="0"><tbody><tr><td style="word-break:break-word;font-size:0px;padding:30px 40px 0px 40px" align="center"><div style="color:#43b581;font-family:Whitney,Helvetica Neue,Helvetica,Arial,Lucida Grande,sans-serif;font-size:18px;font-weight:bold;line-height:16px;text-align:center">KURIOSA #12</div></td></tr><tr><td style="word-break:break-word;font-size:0px;padding:14px 40px 30px 40px" align="center"><div style="color:#737f8d;font-family:Whitney,Helvetica Neue,Helvetica,Arial,Lucida Grande,sans-serif;font-size:16px;line-height:22px;text-align:center">
			In the original Fallout, a player with less than 4 in intelligence can only communicate with grunts and other noises.
		  </div></td></tr></tbody></table></div></td></tr></tbody></table></div>
		  <div style="margin:0px auto;max-width:640px;background:transparent"><table style="font-size:0px;width:100%;background:transparent" cellspacing="0" cellpadding="0" border="0" align="center"><tbody><tr><td style="text-align:center;vertical-align:top;direction:ltr;font-size:0px;padding:20px 0px"><div style="vertical-align:top;display:inline-block;direction:ltr;font-size:13px;text-align:left;width:100%"><table width="100%" cellspacing="0" cellpadding="0" border="0"><tbody><tr><td style="word-break:break-word;font-size:0px;padding:0px" align="center"><div style="color:#99aab5;font-family:Whitney,Helvetica Neue,Helvetica,Arial,Lucida Grande,sans-serif;font-size:12px;line-height:24px;text-align:center">
		  Sent By Discord • <a target="_blank" style="color:#1eb0f4;text-decoration:none" href="discord.com">check out our blog</a> • <a target="_blank" style="color:#1eb0f4;text-decoration:none" href="discord.com">@discordapp</a>
		</div></td></tr><tr><td style="word-break:break-word;font-size:0px;padding:0px" align="center"><div style="color:#99aab5;font-family:Whitney,Helvetica Neue,Helvetica,Arial,Lucida Grande,sans-serif;font-size:12px;line-height:24px;text-align:center">
		  444 De Haro Street, Suite 200, San Francisco, CA 94107
		</div></td></tr><tr><td style="word-break:break-word;font-size:0px;padding:0px" align="left"><div style="color:#000000;font-family:Whitney,Helvetica Neue,Helvetica,Arial,Lucida Grande,sans-serif;font-size:13px;line-height:22px;text-align:left">
			<img src="https://discordapp.com/api/science/642073818218889226/371f0b49-5c8b-4e8d-bd35-96520d1bc9e7.gif?properties=eyJlbWFpbF90eXBlIjogInVzZXJfaXBfYXV0aG9yaXplIn0%3D" width="1" height="1">
		  </div></td></tr></tbody></table></div></td></tr></tbody></table></div></div>
	<img src="http://email.mailgun.discordapp.com/o/eJwVzDkOwyAQQNHThBIxMGwFRSyRe7DFJrLBMsn9g4tf_OZlhwUzRFIdZ2ABZlwIZijQ5ekB50mP_sWFeSA7Qt3XX6O5jtSvHM6Tpn6QzcVomWFKpiyCNTEwnRJqA-8ildIGyeVC-_ZGt_ApjfZ9jN4muN7ibfwBMOAoug" alt width="1px" height="1px"></div>
	</div></div>